spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

# Log for springframework
logging:
  level:
    org.springframework.web: INFO
    org.springframework.core: INFO
    org.hibernate: ERROR